<?php
// $Id: openpgp_gpg.module,v 1.2 2009/09/16 16:39:53 arto Exp $

//////////////////////////////////////////////////////////////////////////////
// Module settings

define('GNUPG_LINK', 'http://www.gnupg.org/');

//////////////////////////////////////////////////////////////////////////////
// Core API hooks

/**
 * Implementation of hook_help().
 */
function openpgp_gpg_help($path) {
  switch ($path) {
    case 'admin/settings/openpgp/gpg':
      return '<p>'. t('<a href="@gnupg" target="_blank">GNU Privacy Guard</a> is the GNU project\'s complete and free implementation of the OpenPGP standard as defined in RFC 4880. GnuPG, also known as GPG, is a command-line tool available for Linux, BSD, Mac OS X and Windows systems.', array('@gnupg' => GNUPG_LINK)) . '</p>';
  }
}

/**
 * Implementation of hook_menu().
 */
function openpgp_gpg_menu() {
  return array(
    // Administer >> Site configuration >> Cryptography >> GnuPG
    'admin/settings/openpgp/gpg' => array(
      'title' => 'GnuPG',
      'type' => MENU_LOCAL_TASK,
      'access arguments' => array('administer OpenPGP configuration'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('openpgp_gpg_admin_settings'),
      'file' => 'openpgp_gpg.admin.inc',
    ),
  );
}

//////////////////////////////////////////////////////////////////////////////
// OpenPGP API hooks

/**
 * Implementation of hook_openpgp_engines().
 */
function openpgp_gpg_openpgp_engines() {
  return array(
    'openpgp_gpg'   => array(
      'title'       => t('GnuPG'),
      'description' => t('<a href="@gnupg" target="_blank">GNU Privacy Guard</a>', array('@gnupg' => GNUPG_LINK)),
      'link'        => GNUPG_LINK,
      'features'    => array('encrypt', 'decrypt'/*, 'sign', 'verify'*/),
      'class'       => 'GnuPG',
      'file'        => 'openpgp_gpg.inc',
      'available'   => TRUE,
    ),
  );
}
