<?php
// $Id: openpgp.module,v 1.6 2009/09/18 10:31:51 arto Exp $

//////////////////////////////////////////////////////////////////////////////
// Module settings

define('OPENPGP_AGENT', 'Drupal (+http://drupal.org/project/openpgp)');

//////////////////////////////////////////////////////////////////////////////
// Core API hooks

/**
 * Implementation of hook_perm().
 */
function openpgp_perm() {
  return array(
    'administer OpenPGP configuration',
    'administer OpenPGP keys',
    'access OpenPGP keys',
  );
}

/**
 * Implementation of hook_menu().
 */
function openpgp_menu() {
  return array(
    // Administer >> Site configuration >> Cryptography
    'admin/settings/openpgp' => array(
      'title' => 'Cryptography',
      'description' => 'Settings for OpenPGP cryptography.',
      'access arguments' => array('administer OpenPGP configuration'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('openpgp_admin_settings'),
      'file' => 'openpgp.admin.inc',
    ),
    'admin/settings/openpgp/configure' => array(
      'title' => 'Configure',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => -10,
    ),

    // Administer >> User management >> Public keys
    'admin/user/openpgp' => array(
      'title' => 'Public keys',
      'description' => 'Manage the OpenPGP public keys of your users.',
      'access arguments' => array('administer OpenPGP keys'),
      'page callback' => 'openpgp_admin_users',
      'file' => 'openpgp.admin.inc',
    ),
    // My account >> Download OpenPGP key
    'user/%user/openpgp' => array(
      'type' => MENU_CALLBACK,
      'access arguments' => array('access OpenPGP keys'),
      'page callback' => 'openpgp_output_user_key',
      'page arguments' => array(1),
    ),
  );
}

/**
 * Implementation of hook_theme().
 */
function openpgp_theme() {
  return array(
    'openpgp_key_block' => array(
      'arguments' => array('text' => NULL, 'account' => NULL),
    ),
  );
}

//////////////////////////////////////////////////////////////////////////////
// User API hooks

/**
 * Implementation of hook_user().
 */
function openpgp_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'validate':
      return openpgp_user_validate($edit, $account, $category);
    case 'submit':
      return openpgp_user_submit($edit, $account, $category);
    case 'form':
      return openpgp_user_form($edit, $account, $category);
  }
}

/**
 * Implementation of hook_user('validate').
 */
function openpgp_user_validate(&$edit, &$account, $category = NULL) {
  if ($category != NULL && ($field = openpgp_get_profile_field()) && $category == $field->category) {
    if (isset($edit[$field->name])) {
      if (($key_ascii = $edit[$field->name] = trim($edit[$field->name]))) {
        if (!($key_binary = openpgp_unarmor($key_ascii))) {
          form_set_error($field->name, t('Invalid OpenPGP key. Enter an ASCII-armored key beginning with <tt>-----BEGIN PGP PUBLIC KEY BLOCK-----</tt> and ending with <tt>-----END PGP PUBLIC KEY BLOCK-----</tt>'));
        }
      }
    }
  }
}

/**
 * Implementation of hook_user('submit').
 */
function openpgp_user_submit(&$edit, &$account, $category = NULL) {
  if ($category != NULL && ($field = openpgp_get_profile_field()) && $category == $field->category) {
    if (isset($edit[$field->name])) {
      $key = openpgp_get_user_key($edit);
      $edit['openpgp_key_id']          = $key ? $key->key_id      : NULL;
      $edit['openpgp_key_fingerprint'] = $key ? $key->fingerprint : NULL;
    }
  }
}

/**
 * Implementation of hook_user('form').
 */
function openpgp_user_form(&$edit, &$account, $category = NULL) {
  switch ($category) {
    case 'account':
      $form = array();
      if (($encrypt = variable_get('openpgp_mail_encrypt', '')) != '') {
        if (!module_exists('contact')) {
          $form['contact'] = array(
            '#type'          => 'fieldset',
            '#title'         => t('Contact settings'),
            '#weight'        => 5,
            '#collapsible'   => TRUE,
          );
        }
        $form['contact']['openpgp_mail_encrypt'] = array(
          '#type'          => 'checkbox',
          '#title'         => t('Encrypt e-mail sent to me (when possible)'),
          '#default_value' => ($encrypt == 'always') ? 1 : (isset($edit['openpgp_mail_encrypt']) ? $edit['openpgp_mail_encrypt'] : 1),
          '#description'   => t('Check this box if you prefer to receive <a href="@openpgp" target="_blank">OpenPGP</a>-compatible encrypted e-mails.', array('@openpgp' => 'http://drupal.org/project/openpgp')),
          '#disabled'      => ($encrypt == 'always'),
        );
      }
      return $form;
  }
}

/**
 * Implementation of hook_form_alter('user_profile_form').
 */
function openpgp_form_user_profile_form_alter(&$form, $form_state, $form_id = 'user_profile_form') {
  if (($category = $form['_category']['#value']) == openpgp_get_profile_category()) {
    // TODO: set field description if it doesn't already have any?
  }
}

/**
 * Implementation of hook_profile_alter().
 */
function openpgp_profile_alter(&$account) {
  if (($field = openpgp_get_profile_field()) && isset($account->content[$field->category])) {
    $form = &$account->content[$field->category];

    if (!user_access('access OpenPGP keys')) {
      unset($form[$field->name]);
    }
    else if (isset($form[$field->name]) && isset($account->{$field->name})) {
      $form[$field->name]['#value'] = theme('openpgp_key_block', $account->{$field->name}, $account);
      $form[$field->name]['#title'] .= ' <small>(' . l(t('download'), 'user/' . $account->uid . '/openpgp') . ')</small>';
    }
  }
}

//////////////////////////////////////////////////////////////////////////////
// Mail API hooks

/**
 * Implementation of hook_mail_alter().
 */
function openpgp_mail_alter(&$message) {
  if (variable_get('openpgp_mail_encrypt', FALSE)) {
    if (($recipients = openpgp_mail_get_recipients($message))) {
      if (openpgp_mail_enabled($recipients)) {
        openpgp_mail_encrypt($message, $recipients);
      }
    }
  }
}

function openpgp_mail_get_recipients(&$message) {
  switch ($message['id']) {
    case 'user_register_admin_created':
    case 'user_register_no_approval_required':
    case 'user_register_pending_approval':
    case 'user_password_reset':
    case 'user_status_activated':
    case 'user_status_blocked':
    case 'user_status_deleted':
      return array($message['params']['account']);
    case 'contact_user_mail':
      return array($message['params']['recipient']);
    case 'contact_user_copy':
      return array($message['params']['user']);
    case 'contact_page_mail':
    default:
      return openpgp_mail_parse_recipients($message['to']);
  }
}

function openpgp_mail_parse_recipients($addresses) {
  $recipients = array();
  foreach (is_array($addresses) ? $addresses : explode(',', $addresses) as $recipient) {
    $recipient = trim(preg_match('/<([^>]+)>/', $recipient, $matches) ? $matches[1] : $recipient);

    if (($account = user_load(array('mail' => $recipient)))) {
      $recipients[$account->uid] = $account;
    }
    else {
      $recipients[$recipient] = $recipient; // TODO: look it up on the keyservers?
    }
  }
  return $recipients;
}

function openpgp_mail_encrypt(&$message, $recipients) {
  $plaintext  = is_array($message['body']) ? implode("\n\n", $message['body']) : $message['body'];
  $recipients = is_array($recipients) ? $recipients : array($recipients);
  $options    = ($comment = variable_get('openpgp_mail_comment', '')) ? array('comment' => $comment) : array();

  if (($ciphertext = openpgp_encrypt($plaintext, $recipients, $options))) {
    $message['body'] = $ciphertext;

    if (($header = variable_get('openpgp_mail_header', ''))) {
      $message['body'] = $header . "\n\n" . $message['body'];
    }

    if (($footer = variable_get('openpgp_mail_footer', ''))) {
      $message['body'] .= "\n" . $footer;
    }

    if (OPENPGP_AGENT) {
      $message['headers']['X-PGP-Agent'] = OPENPGP_AGENT;
    }
  }
  else {
    watchdog('mail', 'Error encrypting e-mail (from %from to %to): <pre>@error</pre>', array('%from' => $message['from'], '%to' => $message['to'], '@error' => GnuPG::$output), WATCHDOG_WARNING, l(t('configure'), 'admin/settings/openpgp'));
  }
}

function openpgp_mail_enabled($accounts) {
  $result = ($encrypt = variable_get('openpgp_mail_encrypt', '')) != '';
  if ($encrypt == 'custom') {
    foreach ($accounts as $account) {
      $result = $result && !empty($account->openpgp_mail_encrypt);
    }
  }
  return $result;
}

//////////////////////////////////////////////////////////////////////////////
// Lockdown API hooks

/**
 * Implementation of hook_lockdown_settings().
 */
function openpgp_lockdown_settings($op) {
  switch ($op) {
    case 'variables':
      return array('messaging' => array('openpgp_mail_encrypt'));

    case 'form':
      module_load_include('inc', 'openpgp', 'openpgp.admin');
      $form = openpgp_admin_settings();
      return array('openpgp_mail_encrypt' => $form['mail']['openpgp_mail_encrypt']);

    case 'validate':
      break;
  }
}

//////////////////////////////////////////////////////////////////////////////
// OpenPGP API implementation

/**
 * Encrypts the given plaintext using the specified public key ID(s).
 */
function openpgp_encrypt($plaintext, $keys, array $options = array()) {
  if (!module_exists('openpgp_gpg')) return FALSE;
  module_load_include('inc', 'openpgp', 'openpgp');
  module_load_include('inc', 'openpgp_gpg', 'openpgp_gpg');

  return ($keys = openpgp_parse_keys($keys)) ? GnuPG::encrypt($plaintext, $keys, $options) : FALSE;
}

/**
 * Decrypts the given ciphertext using the specified key ID.
 */
function openpgp_decrypt($ciphertext, $keys = NULL, array $options = array()) {
  if (!module_exists('openpgp_gpg')) return FALSE;
  module_load_include('inc', 'openpgp', 'openpgp');
  module_load_include('inc', 'openpgp_gpg', 'openpgp_gpg');

  return GnuPG::decrypt($ciphertext, $keys ? openpgp_parse_keys($keys) : NULL, $options);
}

/**
 * Parses a binary or ASCII-armored OpenPGP message into its constituent
 * packets.
 */
function openpgp_parse($input) {
  module_load_include('inc', 'openpgp', 'openpgp');

  if (strpos($input = (string)$input, '-----BEGIN') !== FALSE) {
    if (!($input = openpgp_unarmor($input))) {
      return FALSE; // unarmoring failed
    }
  }
  return OpenPGP_Message::parse($input);
}

/**
 * Decodes an ASCII-armored OpenPGP message into the binary message format.
 */
function openpgp_unarmor($ascii) {
  module_load_include('inc', 'openpgp', 'openpgp');

  return OpenPGP::unarmor($ascii);
}

//////////////////////////////////////////////////////////////////////////////
// OpenPGP API helpers

function openpgp_parse_keys($keys) {
  $profile_field = openpgp_get_profile_field_name();

  $keys = is_array($keys) ? $keys : array($keys);
  foreach ($keys as $index => $key) {
    if (is_object($key)) {
      if (isset($key->uid)) {
        $key = user_load($key->uid); // needed to prevent missing profile field in some contexts
      }
      if ($profile_field && !empty($key->$profile_field) && openpgp_unarmor($key->$profile_field)) { // a user object
        $keys[$index] = $key = GnuPG::import_key($key->$profile_field);
        //$keys[$index] = $key = openpgp_get_user_key($key);
      }
      if ($key instanceof OpenPGP_PublicKeyPacket) {
        $keys[$index] = $key = $key->fingerprint;
      }
    }
  }
  return $keys;
}

function openpgp_get_user_key($account = NULL) {
  if (($field = openpgp_get_profile_field_name())) {
    $account = (object)($account ? $account : $GLOBALS['user']);
    return !empty($account->$field) ? openpgp_get_public_key_packet(openpgp_parse($account->$field)) : NULL;
  }
}

function openpgp_get_profile_category() {
  return ($field = openpgp_get_profile_field()) ? $field->category : NULL;
}

function openpgp_get_profile_field() {
  return db_fetch_object(db_query("SELECT * FROM {profile_fields} WHERE name = '%s'", openpgp_get_profile_field_name()));
}

function openpgp_get_profile_field_name() {
  return variable_get('openpgp_profile_field', '');
}

function openpgp_get_profile_fields() {
  $fields = array();
  $result = db_query("SELECT * FROM {profile_fields} WHERE type = 'textarea' ORDER BY category, weight");
  while ($field = db_fetch_object($result)) {
    $fields[$field->category][$field->name] = "{$field->title} ({$field->name})";
  }
  return $fields;
}

function openpgp_get_engine_class($name = 'openpgp_gpg') {
  if (($engine = openpgp_get_engine($name))) {
    // TODO
  }
}

function openpgp_get_engine($name = 'openpgp_gpg') {
  $engines = openpgp_get_engines();
  return isset($engines[$name]) ? $engines[$name] : NULL;
}

function openpgp_get_engines() {
  return module_invoke_all('openpgp_engines');
}

function openpgp_get_public_key_id($msg) {
  return ($packet = openpgp_get_public_key_packet($msg)) ? $packet->key_id : FALSE;
}

function openpgp_get_public_key_packet($msg) {
  return openpgp_get_packet($msg, 'OpenPGP_PublicKeyPacket');
}

function openpgp_get_packet($msg, $packet_class) {
  module_load_include('inc', 'openpgp', 'openpgp');

  if ($msg instanceof OpenPGP_Message) {
    foreach ($msg as $packet) {
      if ($packet instanceof $packet_class) {
        return $packet;
      }
    }
  }
}

//////////////////////////////////////////////////////////////////////////////
// Theme callbacks

/**
 * Theme callback: Output an OpenPGP key block.
 */
function theme_openpgp_key_block($text, $account = NULL) {
  // Wrap the OpenPGP key block in <pre>...</pre> tags to ensure it is
  // displayed using an appropriate fixed-width font:
  return '<div class="openpgp key">' . "<pre>\n" . check_plain($text) . "\n</pre></div>"; // TODO: RDFa
}

//////////////////////////////////////////////////////////////////////////////
// Menu callbacks

/**
 * Menu callback: Output a user's OpenPGP key in ASCII-armored format.
 */
function openpgp_output_user_key($account, $action = 'download') {
  if (in_array($action, array('download', 'view')) && ($field = openpgp_get_profile_field_name()) && isset($account->$field)) {
    $key_ascii = $account->$field;

    // @see http://tools.ietf.org/html/rfc3156#section-7
    drupal_set_header('Content-Type: ' . ($action == 'download' ? 'application/pgp-keys' : 'text/plain; charset=us-ascii'));
    drupal_set_header('Content-Disposition: ' . ($action == 'download' ? 'attachment' : 'inline') . '; filename=' . (isset($account->openpgp_key_id) ? strtoupper($account->openpgp_key_id) : 'OpenPGP') . '.asc');
    drupal_set_header('Content-SHA1: ' . ($sha1 = sha1($key_ascii)));
    drupal_set_header('Content-MD5: ' . md5($key_ascii));
    drupal_set_header('Content-Length: ' . strlen($key_ascii));
    drupal_set_header('ETag: "' . $sha1 . '"');

    die($key_ascii);
  }
  return drupal_not_found();
}
